pipeline {
    agent any  // This means the pipeline will run on any available Jenkins agent

    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from your GitHub repository
                git branch: 'jenkins', url: 'https://github.com/Ashikasalian/devops_project.git'
            }
        }

        stage('Build') {
            steps {
                // Run the Maven build command
                sh 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                // Run tests using Maven
                sh 'mvn test'
            }
        }

        stage('Deploy') {
            steps {
                // Placeholder for deployment steps
                echo 'Deploying the application...'
            }
        }
    }

    post {
        success {
            echo 'Build and tests completed successfully!'
        }

        failure {
            echo 'Build or tests failed.'
        }
    }
}
