
pipeline {

    agent any

    stages{
        stage('git checkout'){
            steps{
                git branch: 'main', url: 'https://github.com/Ashikasalian/devops_project.git'

            }
        }

    post {
        success {
            echo 'Build and tests successful!'
        }

        failure {
            echo 'Build or tests failed.'
        }

        always {
            echo 'Cleaning up...'
        }
    }
}
}
